---
title: "Sexual identity and health outcomes in Stockholm County, SPHC-B 2010"
author: Willi Zhang
email: willi.zhang@ki.se
output: html_notebook
editor_options: 
  chunk_output_type: console
---

### 1. Load Packages
```{r}
library(haven)
library(tidyr)
library(tidyverse)
library(dplyr)
library(finalfit)
library(lubridate)
library(stringr)
library(ggplot2)
library(naniar)
library(jomo)
library(mitml)
library(mitools)
library(survey)
library(svyVGAM)
library(vcd)
library(rcompanion)
source('Helper_functions.R') # helper function
```

### 2. Import and Prepare Data
```{r}
load('/Volumes/LGBT Project data/d_2010.RData')

# sampling strata
n_miss( d_2010$stratum )
d_2010$sampling_strata <- as.factor( d_2010$stratum )
length( unique( d_2010$sampling_strata ) ) # 39 strata

d_2010 <- d_2010 %>%
  mutate( sampling_strata_region = recode( sampling_strata, 
                                           `2101` = "Upplands-Väsby",
                                           `2102` = "Vallentuna",
                                           `2103` = "Österåker",
                                           `2104` = "Värmdö",
                                           `2105` = "Järfälla",
                                           `2106` = "Ekerö",
                                           `2107` = "Huddinge",
                                           `2108` = "Botkyrka",
                                           `2109` = "Salem",
                                           `2110` = "Haninge",
                                           `2111` = "Tyresö",
                                           `2112` = "Upplands-Bro",
                                           `2113` = "Nykvarn",
                                           `2114` = "Täby",
                                           `2115` = "Danderyd",
                                           `2116` = "Sollentuna",
                                           `2117` = "Södertälje",
                                           `2118` = "Nacka",
                                           `2119` = "Sundbyberg",
                                           `2120` = "Solna",
                                           `2121` = "Lidingö",
                                           `2122` = "Vaxholm",
                                           `2123` = "Norrtälje",
                                           `2124` = "Sigtuna",
                                           `2125` = "Nynäshamn",
                                           `2201` = "Rinkeby-Kista",
                                           `2202` = "Spånga-Tensta",
                                           `2203` = "Hässelby-Vällingby",
                                           `2204` = "Bromma",
                                           `2205` = "Kungsholmen",
                                           `2206` = "Norrmalm",
                                           `2207` = "Östermalm",
                                           `2208` = "Södermalm",
                                           `2209` = "Enskede-Årsta-Vantör",
                                           `2210` = "Skarpnäck",
                                           `2211` = "Farsta",
                                           `2212` = "Älvsjö",
                                           `2213` = "Hägersten-Liljeholmen",
                                           `2214` = "Skärholmen"
                                           ) )

# sexual identity in 2010
table( d_2010$F10U87G78, useNA = "always" )
d_2010$F10U87G78[ d_2010$F10U87G78 == 9 ] <- NA
d_2010$sexual_identity_2010 <- factor( ifelse( d_2010$F10U87G78 == 1, "Heterosexual",
                                                  ifelse( d_2010$F10U87G78 == 2, "Homosexual",
                                                          ifelse( d_2010$F10U87G78 == 3, "Bisexual", "Uncertain" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Uncertain" ) )
table( d_2010$sexual_identity_2010, useNA = "always" )

# sexual identity in 2014
table( d_2010$F14F103, useNA = "always" )
d_2010$sexual_identity_2014 <- factor( ifelse( d_2010$F14F103 == 1, "Heterosexual",
                                                  ifelse( d_2010$F14F103 == 2, "Homosexual",
                                                          ifelse( d_2010$F14F103 == 3, "Bisexual", "None of the above" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "None of the above" ) )
table( d_2010$sexual_identity_2014, useNA = "always" )

# sexual identity in 2021
table( d_2010$F21F91, useNA = "always" )
d_2010$sexual_identity_2021 <- factor( ifelse( d_2010$F21F91 == 1, "Heterosexual",
                                                  ifelse( d_2010$F21F91 == 2, "Homosexual",
                                                          ifelse( d_2010$F21F91 == 3, "Bisexual", "None of the above" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "None of the above" ) )
table( d_2010$sexual_identity_2021, useNA = "always" )

# sex
table( d_2010$kon, useNA = "always" )
d_2010$sex <- factor( ifelse( d_2010$kon == 1, "Male", "Female" ),
                      levels = c( "Male", "Female" ) )
table( d_2010$sex, useNA = "always" )

# age
summary( d_2010$F10alder )
d_2010$age <- d_2010$F10alder
d_2010$age_cat <- factor( ifelse( d_2010$age <= 29, "18-29", 
                                  ifelse( d_2010$age >=30 & d_2010$age <= 44, "30-44",
                                          ifelse( d_2010$age >= 45 & d_2010$age <= 59, "45-59", ">=60" ) ) ),
                          levels = c( "18-29", "30-44", "45-59", ">=60" ) )
table( d_2010$age_cat, useNA = "always" )

# interaction term between age and sex
d_2010$age_sex <- interaction( d_2010$age_cat, d_2010$sex )

# generation
d_2010$birth_year <- 2010 - d_2010$age
d_2010 <- d_2010 %>%
  mutate( generation = case_when(
    birth_year >= 1981 & birth_year <= 1996 ~ "Millennials (1981–1996)",
    birth_year >= 1965 & birth_year <= 1980 ~ "Generation X (1965–1980)",
    birth_year >= 1946 & birth_year <= 1964 ~ "Baby Boomers (1946–1964)",
    birth_year >= 1928 & birth_year <= 1945 ~ "Silent Generation (1928–1945)",
    birth_year >= 1901 & birth_year <= 1927 ~ "Greatest Generation (1901–1927)"
    ) )

d_2010$generation <- factor( 
  d_2010$generation, 
  levels = c( "Millennials (1981–1996)", "Generation X (1965–1980)", "Baby Boomers (1946–1964)", "Silent Generation (1928–1945)", "Greatest Generation (1901–1927)" ) )
summary( d_2010$generation )

# country of birth
table( d_2010$fodelseland, useNA = "always" )
d_2010$country_of_birth <- factor( ifelse( d_2010$fodelseland == "Sverige", "Sweden",
                                           ifelse( d_2010$fodelseland == "Europa", "Europe", "Outside Europe" ) ),
                                   levels = c( "Sweden", "Europe", "Outside Europe" ) )
table( d_2010$country_of_birth, useNA = "always" )

# education
table( d_2010$utbniva2010, useNA = "always" )
d_2010$education <- factor( ifelse( d_2010$utbniva2010 <= 2, "<=9 years",
                                    ifelse( d_2010$utbniva2010 <= 4, "10-12 years", ">=13 years" ) ), 
                            levels = c( "<=9 years", "10-12 years", ">=13 years" ) )
table( d_2010$education, useNA = "always" )

# occupation
table( d_2010$SSYK_kl, useNA = "always" )
d_2010$occupation <- factor(
  ifelse(
    d_2010$SSYK_kl == "Yrken inom byggverksamhet och tillverkning" |
      d_2010$SSYK_kl == "Yrken inom lantbruk, trädgård, skogsbruk och fiske" |
      d_2010$SSYK_kl == "Yrken inom maskinell tillverkning och transport m.m.",
    "Manual and field trades",
    ifelse(
      d_2010$SSYK_kl == "Service-, omsorgs- och försäljningsyrken" |
        d_2010$SSYK_kl == "Yrken inom administration och kundtjänst" |
        d_2010$SSYK_kl == "Yrken med krav på kortare utbildning eller introduktion",
      "Service and support",
      ifelse(
        d_2010$SSYK_kl == "Yrken med krav på fördjupad högskolekompetens" |
          d_2010$SSYK_kl == "Yrken med krav på högskolekompetens eller motsvarande" |
          d_2010$SSYK_kl == "Chefsyrken" |
          d_2010$SSYK_kl == "Militära yrken",
        "Expertise and leadership",
        NA
      )
    )
  ),
  levels = c(
    "Manual and field trades",
    "Service and support",
    "Expertise and leadership"
  )
)
table( d_2010$occupation, useNA = "always" )

# disposable income
summary( d_2010$dispink2010, useNA = "always" )
d_2010$dispink2010 <- d_2010$dispink2010*( 343.19/303.46 ) # Consumer Price Index (CPI)-adjusted income (https://www.statistikdatabasen.scb.se/pxweb/en/ssd/START__PR__PR0101__PR0101L/KPIFastAmed/table/tableViewLayout1/)
d_2010$income <- factor( ifelse( d_2010$dispink2010 <= 2500, "<=2,500",
                                 ifelse( d_2010$dispink2010 > 2500 & d_2010$dispink2010 <= 3500, "(2,500, 3,500]",
                                         ifelse( d_2010$dispink2010 > 3500 & d_2010$dispink2010 <= 4500, "(3,500, 4,500]", ">4,500" ) ) ),
                         levels = c( "<=2,500", "(2,500, 3,500]", "(3,500, 4,500]", ">4,500" ) )
table( d_2010$income, useNA = "always" )

# marital status
table( d_2010$civil2010, useNA = "always" )
d_2010$marital_status <- factor( ifelse( d_2010$civil2010 == "G" | d_2010$civil2010 == "RP", "Currently married",
                                         ifelse( d_2010$civil2010 == "OG", "Never married", "Other" ) ), 
                                 levels = c( "Never married", "Currently married", "Other" ) )
table( d_2010$marital_status, useNA = "always" )


##### demographic characteristics #####

# among respondents (n = 30,767)
# make characteristics table by sexual identity
explanatory =  c( "sex", "age_cat", "country_of_birth", "education", "occupation", "income", "marital_status" )
dependent = "sexual_identity_2010"

d_2010_table_1 <- d_2010 %>% 
  summary_factorlist( dependent,
                      explanatory, 
                      na_include = TRUE,
                      na_include_dependent = TRUE, 
                      total_col = TRUE,
                      add_col_totals = TRUE,
                      column = FALSE )

# Fisher's test
x1 <- table( d_2010$sex, d_2010$sexual_identity_2010 )
x1
format( round( fisher.test( x1[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x1[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x1[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )

x2 <- table( d_2010$age_cat, d_2010$sexual_identity_2010 )
x2
format( round( fisher.test( x2[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x2[, c( 1, 3 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x2[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )

x3 <- table( d_2010$country_of_birth, d_2010$sexual_identity_2010 )
x3
format( round( fisher.test( x3[, c( 1, 2 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x3[, c( 1, 3 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x3[, c( 1, 4 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

x4 <- table( d_2010$education, d_2010$sexual_identity_2010 )
x4
format( round( fisher.test( x4[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x4[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x4[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )

x5 <- table( d_2010$income, d_2010$sexual_identity_2010 )
x5
format( round( fisher.test( x5[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x5[, c( 1, 3 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x5[, c( 1, 4 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

x6 <- table( d_2010$marital_status, d_2010$sexual_identity_2010 )
x6
format( round( fisher.test( x6[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x6[, c( 1, 3 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x6[, c( 1, 4 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

x7 <- table( d_2010$occupation, d_2010$sexual_identity_2010 )
x7
format( round( fisher.test( x7[, c( 1, 2 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x7[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x7[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )


##### design weights #####

summary( d_2010$F10dvikt )
d_2010$design_weight <- d_2010$F10dvikt


##### calibrated weights #####

d_2010$calibrated_weight <- d_2010$F10kalvikt


##### non-response #####

# unit non-response
d_2010$design_weight_unit_nonresponse <- d_2010$F10dbvikt # weights calculated assuming Missing Completely At Random (MCAR) within each stratum
summary( d_2010$design_weight_unit_nonresponse )
sum( d_2010$design_weight_unit_nonresponse ) # No. of source population = 1,602,868

unitresponse_prob <- d_2010 %>% 
  group_by( sampling_strata_region ) %>% 
  summarise( unitresponse_prob = unique( design_weight ) / unique( design_weight_unit_nonresponse ),
             no.of.population = sum( design_weight_unit_nonresponse ),
             sample_size = unique( no.of.population )/unique( design_weight ) ) # calculate overall unit response rate, and no. of population and sample size within each stratum
d_2010 <- d_2010 %>% 
  left_join( unitresponse_prob, by = "sampling_strata_region" )

# item non-response
itemresponse_prob <- d_2010 %>% 
  group_by( sampling_strata_region ) %>% 
  summarise( itemresponse_prob = sum( !is.na( sexual_identity_2010 ) ) / n() ) # calculate item response rate

d_2010 <- d_2010 %>% 
  left_join( itemresponse_prob, by = "sampling_strata_region" ) %>% 
  mutate( itemresponse_prob = ifelse( is.na( sexual_identity_2010 ), 0, itemresponse_prob ) )


##### summary of stratified sampling #####

sampling_frame_2010 <- as.data.frame( d_2010 %>% 
                                   group_by( sampling_strata_region ) %>% 
                                   reframe( no.of.population = unique( no.of.population ), 
                                            sample_size = unique( no.of.population/design_weight ),
                                            unitresponse = n(),
                                            itemresponse = sum( itemresponse_prob != 0 ) ) )

sampling_frame_2010$unitresponse_rate <- sampling_frame_2010$unitresponse/sampling_frame_2010$sample_size
sampling_frame_2010$itemresponse_rate <- sampling_frame_2010$itemresponse/sampling_frame_2010$unitresponse
sampling_frame_2010$overallresponse_rate <- sampling_frame_2010$itemresponse/sampling_frame_2010$sample_size

sampling_frame_2010$unitresponse_label <- paste0( sampling_frame_2010$unitresponse, " (", 
                                             sprintf( "%.1f", sampling_frame_2010$unitresponse_rate*100 ), "%)" )
sampling_frame_2010$overallresponse_label <- paste0( sampling_frame_2010$itemresponse, " (", 
                                                sprintf( "%.1f", sampling_frame_2010$overallresponse_rate*100 ), "%)" )

round( sum( sampling_frame_2010$unitresponse )/( sum( sampling_frame_2010$sample_size ) ), 3 ) # overall unit response rate
round( sum( sampling_frame_2010$itemresponse )/( sum( sampling_frame_2010$unitresponse ) ), 3 ) # overall item response rate
round( sum( sampling_frame_2010$itemresponse )/( sum( sampling_frame_2010$sample_size ) ), 3 ) # overall response rate

writexl::write_xlsx( sampling_frame_2010, "sampling_frame_2010.xlsx" )


##### replicating non-respondent rows for sampling design #####

# because d_2010 includes data only for respondents (unit response), we need to duplicate rows for non-respondents
# so that the final dataset represents the sampling process
rows_to_add <- d_2010 %>%
  group_by( sampling_strata_region ) %>%
  summarise( to_add = unique( sample_size ) - n(),
             no.of.population = unique( no.of.population ),
             sample_size = unique( sample_size ),
             design_weight = unique( design_weight ) )

rows_to_add$to_add <- round( rows_to_add$to_add )

sum( rows_to_add$to_add ) # 24,573 non-respondents

replicated_rows <- rows_to_add[ rep( row.names( rows_to_add ), rows_to_add$to_add ), c( 1, 3:5 ) ]

d_2010_complete <- bind_rows( d_2010, replicated_rows ) # 55,340 individuals in the original sample
```

### 3. Self-Reported Health Outcomes
#### 3.1. Complete-case analysis
##### 3.1.1. Prepare dataset
```{r}
##### mental health outcomes #####

# recent psychological distress
summary( d_2010_complete$F10GHQ12 )
d_2010_complete$psychological_distress <- factor( ifelse( d_2010_complete$F10GHQ12 >= 3, "Yes", "No" ),
                                                  levels = c( "Yes", "No" ) ) # psychological distress defined as a score >= 3
table( d_2010_complete$psychological_distress, useNA = "always" )

# suicidal thoughts
table( d_2010_complete$F10U51G55, useNA = "always" )
d_2010_complete$F10U51G55[ d_2010_complete$F10U51G55 == 9 ] <- NA
d_2010_complete$suicidal_thoughts <- factor( 
  case_when(
    d_2010_complete$F10U51G55 == 1 ~ "No",
    d_2010_complete$F10U51G55 %in% c( 2, 3, 4 ) ~ "Yes"
  ),
  levels = c( "Yes", "No" ) )
table( d_2010_complete$suicidal_thoughts, useNA = "always" )

# suicide attempts
table( d_2010_complete$F10U52G56, useNA = "always" )
d_2010_complete$F10U52G56[ d_2010_complete$F10U52G56 == 9 ] <- NA
d_2010_complete$suicide_attempts <- factor( 
  case_when(
    d_2010_complete$F10U52G56 == 1 ~ "No",
    d_2010_complete$F10U52G56 %in% c( 2, 3, 4 ) ~ "Yes"
  ),
  levels = c( "Yes", "No" ) )
table( d_2010_complete$suicide_attempts, useNA = "always" )


##### behavioral health outcomes #####

# ever cannabis use
table( d_2010_complete$U31, useNA = "always" )
d_2010_complete$U31[ d_2010_complete$U31 == 9 ] <- NA
d_2010_complete$cannabis_use <- factor( if_else( d_2010_complete$U31 == 1, "No", "Yes" ),
                                        levels = c( "Yes", "No" ) )
table( d_2010_complete$cannabis_use, useNA = "always" )
```

##### 3.1.2. Calculate prevalence by sexual identity
```{r}
# create survey design
d_2010_complete_cc <- d_2010_complete

survey_design_cc <- svydesign( ids = ~ 1, 
                               strata = ~ sampling_strata_region,
                               weights = ~ design_weight,
                               fpc = ~ no.of.population,
                               data = d_2010_complete_cc )

# the following analyses assume MCAR

variables_list <- list(
  list( variable = "psychological_distress", condition = "Yes", name = "psychological_distress" ),
  list( variable = "suicidal_thoughts", condition = "Yes", name = "suicidal_thoughts" ),
  list( variable = "suicide_attempts", condition = "Yes", name = "suicide_attempts" ),
  list( variable = "cannabis_use", condition = "Yes", name = "cannabis_use" )
  )

# by sexual identity
results_list <- calculate_svyby_proportion( variables_list = variables_list, 
                                            design = survey_design_cc, 
                                            year = 2010, 
                                            group_var = "sexual_identity_2010" )

self_report_health_outcomes_2010 <- Reduce( function( x, y ){
  merge( x, y, by = "sexual_identity_2010" )
}, 
results_list )

# overall sample
results_list_overall <- calculate_svyby_proportion_overall( 
  variables_list = variables_list,
  design = survey_design_cc,
  year = 2010 )

self_report_health_outcomes_2010_overall <- Reduce( function( x, y ){
  cbind( x, y )
}, 
results_list_overall ) %>% 
  as.data.frame() %>%
  rownames_to_column( var = "sexual_identity_2010" )
self_report_health_outcomes_2010_overall[ 1, 1 ] <- "Stockholm County"

writexl::write_xlsx( rbind( self_report_health_outcomes_2010, self_report_health_outcomes_2010_overall ), "prevalence_cc_self_report_health_outcomes_2010.xlsx" )

# by sex
results_list_by_sex <- calculate_svyby_proportion_subgroup( 
  variables_list = variables_list,
  design = survey_design_cc,
  year = 2010,
  group_var = "sexual_identity_2010 + sex" )

self_report_health_outcomes_2010_by_sex <- Reduce( function( x, y ){
  merge( x, y, by = c( "sexual_identity_2010", "sex" ) )
}, 
results_list_by_sex )
writexl::write_xlsx( self_report_health_outcomes_2010_by_sex, "prevalence_cc_self_report_health_outcomes_2010_by_sex.xlsx" )

# by age
results_list_by_age <- calculate_svyby_proportion_subgroup( 
  variables_list = variables_list,
  design = survey_design_cc,
  year = 2010,
  group_var = "sexual_identity_2010 + age_cat" )

self_report_health_outcomes_2010_by_age <- Reduce( function( x, y ){
  merge( x, y, by = c( "sexual_identity_2010", "age_cat" ) )
}, 
results_list_by_age )
writexl::write_xlsx( self_report_health_outcomes_2010_by_age, "prevalence_cc_self_report_health_outcomes_2010_by_age.xlsx" )
```

### 4. Registry-Based Health Outcomes
#### 4.1. Complete-case analysis
##### 4.1.1. Prepare dataset
```{r}
# use of antidepressants and anxiolytics
atc_2002_2014 <- read_sas('/Volumes/LGBT Project data/Swedish Registers/atc_2002_2014.sas7bdat') %>%
  filter( !grepl( "^N05CD", ATC ) ) # include participants who had at least one dispensed prescription of N05B or N06A from 2005-06-30 to 2021-12-31

summary( atc_2002_2014 )
length( unique( atc_2002_2014$lopnr ) ) # 44,963 individuals had any dispensed prescription
unique( atc_2002_2014$ATC )
length( intersect( atc_2002_2014$lopnr, d_2010_complete$lopnr ) ) # 12,646 in SPHC-B 2010

atc_2010 <- atc_2002_2014 %>%
  filter( lopnr %in% d_2010_complete$lopnr ) %>%
  select( "lopnr", "ATC", "EDATUM" ) %>%
  mutate( 
    drug_class = as.factor( 
      case_when(
        grepl( "^N06A", ATC ) ~ "N06A",
        grepl( "^N05B", ATC ) ~ "N05B" ) ),
      year = year( EDATUM ) ) %>%
  filter( year == 2010 )

summary( atc_2010 )
length( unique( atc_2010$lopnr ) ) # 3,579

atc_2010_summary <- atc_2010 %>%
  group_by( lopnr, drug_class ) %>%
  summarise( 
    prescription_count_2010 = n(), 
    prescribed_2010 = ifelse( n() > 0, 1, 0 ),
    .groups = "drop" )

atc_2010_summary_wide <- atc_2010_summary %>%
  pivot_wider(
    names_from = drug_class,
    values_from = c( prescription_count_2010, prescribed_2010 ),
    names_glue = "{.value}_{drug_class}",
    values_fill = 0 
  )

d_2010_complete_cc_linked <- d_2010_complete %>%
  left_join( atc_2010_summary_wide, by = "lopnr" ) %>%
  mutate(
    prescription_count_2010_N06A = replace_na( prescription_count_2010_N06A, 0 ),
    prescription_count_2010_N05B = replace_na( prescription_count_2010_N05B, 0 ),
    prescribed_2010_N06A = factor( replace_na( prescribed_2010_N06A, 0 ), levels = c( 0, 1 ), labels = c( "No", "Yes" ) ),
    prescribed_2010_N05B = factor( replace_na( prescribed_2010_N05B, 0 ), levels = c( 0, 1 ), labels = c( "No", "Yes" ) )
    )

summary( d_2010_complete_cc_linked$prescription_count_2010_N06A )
summary( d_2010_complete_cc_linked$prescription_count_2010_N05B )
table( d_2010_complete_cc_linked$prescribed_2010_N06A )
table( d_2010_complete_cc_linked$prescribed_2010_N05B )
```

##### 4.1.2. Calculate prevalence by sexual identity
```{r}
# create survey design
survey_design_cc <- svydesign( ids = ~ 1, 
                               strata = ~ sampling_strata_region,
                               weights = ~ design_weight,
                               fpc = ~ no.of.population,
                               data = d_2010_complete_cc_linked )

# the following analyses assume MCAR

variables_list <- list(
  list( variable = "prescribed_2010_N06A", condition = "Yes", name = "prescribed_2010_N06A" ),
  list( variable = "prescribed_2010_N05B", condition = "Yes", name = "prescribed_2010_N05B" )
  )

# by sexual identity
results_list <- calculate_svyby_proportion( variables_list = variables_list, 
                                            design = survey_design_cc, 
                                            year = 2010, 
                                            group_var = "sexual_identity_2010" )

pdr_2010 <- Reduce( function( x, y ){
  merge( x, y, by = "sexual_identity_2010" )
}, 
results_list )
```

