---
title: "Trajectory of health outcomes by sexual identity in Stockholm County"
author: Willi Zhang
email: willi.zhang@ki.se
output: html_notebook
editor_options: 
  chunk_output_type: console
---

### 1. Load Packages
```{r}
library(haven)
library(tidyr)
library(tidyverse)
library(dplyr)
library(finalfit)
library(lubridate)
library(stringr)
library(ggplot2)
library(naniar)
library(jomo)
library(mitml)
library(mitools)
```

### 2. The Stockholm Public Health Cohort, 2002-2021
```{r}
### SPHC-B 2002 ### 

d_2002 <- read_sas("/Volumes/LGBT Project data/sphc02_07_10_14_21.sas7bdat")

summary( d_2002$lopnr ) # 7,411 missing

# sexual identity in 2010
table( d_2002$F10F103, useNA = "always" )
d_2002$F10F103[ d_2002$F10F103 == 9 ] <- NA
d_2002$sexual_identity_2010 <- factor( ifelse( d_2002$F10F103 == 1, "Heterosexual",
                                                  ifelse( d_2002$F10F103 == 2, "Homosexual",
                                                          ifelse( d_2002$F10F103 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2002$sexual_identity_2010, useNA = "always" )

# sexual identity in 2014
table( d_2002$F14F103, useNA = "always" )
d_2002$sexual_identity_2014 <- factor( ifelse( d_2002$F14F103 == 1, "Heterosexual",
                                                  ifelse( d_2002$F14F103 == 2, "Homosexual",
                                                          ifelse( d_2002$F14F103 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2002$sexual_identity_2014, useNA = "always" )

# sexual identity in 2021
table( d_2002$F21F91, useNA = "always" )
d_2002$sexual_identity_2021 <- factor( ifelse( d_2002$F21F91 == 1, "Heterosexual",
                                                  ifelse( d_2002$F21F91 == 2, "Homosexual",
                                                          ifelse( d_2002$F21F91 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2002$sexual_identity_2021, useNA = "always" )

# birth year
summary( d_2002$F2alder )
d_2002$birth_year <- 2002 - d_2002$F2alder
summary( d_2002$birth_year )

# sex
table( d_2002$kon, useNA = "always" )
d_2002$sex <- factor( ifelse( d_2002$kon == 1, "Male", "Female" ),
                      levels = c( "Male", "Female" ) )
table( d_2002$sex, useNA = "always" )

# country of birth
table( d_2002$fodelseland, useNA = "always" )
d_2002$fodelseland[ d_2002$fodelseland == "" ] <- NA
d_2002$country_of_birth <- factor( ifelse( d_2002$fodelseland == "Sverige", "Sweden",
                                           ifelse( d_2002$fodelseland == "Europa", "Europe", "Outside Europe" ) ),
                                   levels = c( "Sweden", "Europe", "Outside Europe" ) )
table( d_2002$country_of_birth, useNA = "always" )

d_2002 <- d_2002 %>% 
  filter( !is.na( lopnr) ) # 7,411 in SPHC-B 2002 did not participate in follow-up surveys and therefore excluded

variable_list <- c( "lopnr", "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021", "birth_year", "sex", "country_of_birth" )
summary( d_2002 %>% select( all_of( variable_list ) ) )


### SPHC-B 2006 ###

d_2006 <- read_sas("/Volumes/LGBT Project data/sphc06_10_14_21.sas7bdat")

summary( d_2006$lopnr )

# sexual identity in 2010
table( d_2006$F10F103, useNA = "always" )
d_2006$F10F103[ d_2006$F10F103 == 9 ] <- NA
d_2006$sexual_identity_2010 <- factor( ifelse( d_2006$F10F103 == 1, "Heterosexual",
                                                  ifelse( d_2006$F10F103 == 2, "Homosexual",
                                                          ifelse( d_2006$F10F103 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2006$sexual_identity_2010, useNA = "always" )

# sexual identity in 2014
table( d_2006$F14F103, useNA = "always" )
d_2006$sexual_identity_2014 <- factor( ifelse( d_2006$F14F103 == 1, "Heterosexual",
                                                  ifelse( d_2006$F14F103 == 2, "Homosexual",
                                                          ifelse( d_2006$F14F103 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2006$sexual_identity_2014, useNA = "always" )

# sexual identity in 2021
table( d_2006$F21F91, useNA = "always" )
d_2006$sexual_identity_2021 <- factor( ifelse( d_2006$F21F91 == 1, "Heterosexual",
                                                  ifelse( d_2006$F21F91 == 2, "Homosexual",
                                                          ifelse( d_2006$F21F91 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2006$sexual_identity_2021, useNA = "always" )

# birth year
summary( d_2006$F6alder )
d_2006$birth_year <- 2006 - d_2006$F6alder
summary( d_2006$birth_year )

# sex
table( d_2006$kon, useNA = "always" )
d_2006$sex <- factor( ifelse( d_2006$kon == 1, "Male", "Female" ),
                      levels = c( "Male", "Female" ) )
table( d_2006$sex, useNA = "always" )

# country of birth
table( d_2006$fodelseland, useNA = "always" )
d_2006$country_of_birth <- factor( ifelse( d_2006$fodelseland == "Sverige", "Sweden",
                                           ifelse( d_2006$fodelseland == "Europa", "Europe", "Outside Europe" ) ),
                                   levels = c( "Sweden", "Europe", "Outside Europe" ) )
table( d_2006$country_of_birth, useNA = "always" )

summary( d_2006 %>% select( all_of( variable_list ) ) )


### SPHC-B 2010 ###

load("/Volumes/LGBT Project data/d_2010.RData")

summary( d_2010$lopnr )

# sexual identity in 2010
table( d_2010$F10U87G78, useNA = "always" )
d_2010$F10U87G78[ d_2010$F10U87G78 == 9 ] <- NA
d_2010$sexual_identity_2010 <- factor( ifelse( d_2010$F10U87G78 == 1, "Heterosexual",
                                                  ifelse( d_2010$F10U87G78 == 2, "Homosexual",
                                                          ifelse( d_2010$F10U87G78 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2010$sexual_identity_2010, useNA = "always" )

# sexual identity in 2014
table( d_2010$F14F103, useNA = "always" )
d_2010$sexual_identity_2014 <- factor( ifelse( d_2010$F14F103 == 1, "Heterosexual",
                                                  ifelse( d_2010$F14F103 == 2, "Homosexual",
                                                          ifelse( d_2010$F14F103 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2010$sexual_identity_2014, useNA = "always" )

# sexual identity in 2021
table( d_2010$F21F91, useNA = "always" )
d_2010$sexual_identity_2021 <- factor( ifelse( d_2010$F21F91 == 1, "Heterosexual",
                                                  ifelse( d_2010$F21F91 == 2, "Homosexual",
                                                          ifelse( d_2010$F21F91 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2010$sexual_identity_2021, useNA = "always" )

# birth year
summary( d_2010$F10alder )
d_2010$birth_year <- 2010 - d_2010$F10alder
summary( d_2010$birth_year )

# sex
table( d_2010$kon, useNA = "always" )
d_2010$sex <- factor( ifelse( d_2010$kon == 1, "Male", "Female" ),
                      levels = c( "Male", "Female" ) )
table( d_2010$sex, useNA = "always" )

# country of birth
table( d_2010$fodelseland, useNA = "always" )
d_2010$country_of_birth <- factor( ifelse( d_2010$fodelseland == "Sverige", "Sweden",
                                           ifelse( d_2010$fodelseland == "Europa", "Europe", "Outside Europe" ) ),
                                   levels = c( "Sweden", "Europe", "Outside Europe" ) )
table( d_2010$country_of_birth, useNA = "always" )

summary( d_2010 %>% select( all_of( variable_list ) ) )


### SPHC-B 2014 ###

load("/Volumes/LGBT Project data/d_2014.RData")

summary( d_2014$lopnr )

# sexual identity in 2014
table( d_2014$F14U90G82, useNA = "always" )
d_2014$sexual_identity_2014 <- factor( ifelse( d_2014$F14U90G82 == 1, "Heterosexual",
                                                  ifelse( d_2014$F14U90G82 == 2, "Homosexual",
                                                          ifelse( d_2014$F14U90G82 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2014$sexual_identity_2014, useNA = "always" )

# sexual identity in 2021
table( d_2014$F21F91, useNA = "always" )
d_2014$sexual_identity_2021 <- factor( ifelse( d_2014$F21F91 == 1, "Heterosexual",
                                                  ifelse( d_2014$F21F91 == 2, "Homosexual",
                                                          ifelse( d_2014$F21F91 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2014$sexual_identity_2021, useNA = "always" )

# birth year
summary( d_2014$F14alder )
d_2014$birth_year <- 2014 - d_2014$F14alder
summary( d_2014$birth_year )

# sex
table( d_2014$kon, useNA = "always" )
d_2014$sex <- factor( ifelse( d_2014$kon == 1, "Male", "Female" ),
                      levels = c( "Male", "Female" ) )
table( d_2014$sex, useNA = "always" )

# country of birth
table( d_2014$fodelseland, useNA = "always" )
d_2014$country_of_birth <- factor( ifelse( d_2014$fodelseland == "Sverige", "Sweden",
                                           ifelse( d_2014$fodelseland == "Europa", "Europe", "Outside Europe" ) ),
                                   levels = c( "Sweden", "Europe", "Outside Europe" ) )
table( d_2014$country_of_birth, useNA = "always" )

summary( d_2014 %>% select( any_of( variable_list ) ) )


### SPHC-B 2021 ###

load("/Volumes/LGBT Project data/d_2021.RData")

d_2021 <- d_2021 %>% 
  rename( lopnr = lopnr2 )
summary( d_2021$lopnr )

# sexual identity in 2021
table( d_2021$F21F45_Q57, useNA = "always" )
d_2021$sexual_identity_2021 <- factor( ifelse( d_2021$F21F45_Q57 == 1, "Heterosexual", 
                                          ifelse( d_2021$F21F45_Q57 == 2, "Homosexual",
                                                  ifelse( d_2021$F21F45_Q57 == 3, "Bisexual", "Other" ) ) ),
                                  levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2021$sexual_identity_2021, useNA = "always" )

# birth year
summary( d_2021$F21alder )
d_2021$birth_year <- 2021 - d_2021$F21alder
summary( d_2021$birth_year )

# sex
table( d_2021$kon, useNA = "always" )
d_2021$sex <- factor( ifelse( d_2021$kon == 1, "Male", "Female" ), 
                      levels = c( "Male", "Female" ) )
table( d_2021$sex, useNA = "always" )

# country of birth
table( d_2021$fodelseland, useNA = "always" )
d_2021$country_of_birth <- factor( ifelse( d_2021$fodelseland == "Sverige", "Sweden",
                                           ifelse( d_2021$fodelseland == "Europa", "Europe", "Outside Europe" ) ),
                                   levels = c( "Sweden", "Europe", "Outside Europe" ) )
table( d_2021$country_of_birth, useNA = "always" )

summary( d_2021 %>% select( any_of( variable_list ) ) )
```

### 3. Merge & Prepare Data
```{r}
### SPHC 2002 to 2014 ###

variable_list <- c( "lopnr", "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021", "birth_year", "sex", "country_of_birth" )

d_2002_selected <- d_2002 %>%
  select( any_of( variable_list ) ) %>%
  mutate( survey_year = "SPHC 2002" )

d_2006_selected <- d_2006 %>%
  select( any_of( variable_list ) ) %>%
  mutate( survey_year = "SPHC 2006" )

d_2010_selected <- d_2010 %>%
  select( any_of( variable_list ) ) %>%
  mutate( survey_year = "SPHC 2010" )

d_2014_selected <- d_2014 %>%
  select( any_of( variable_list ) ) %>%
  mutate( survey_year = "SPHC 2014" )

pre2021 <- bind_rows(
  d_2002_selected,
  d_2006_selected,
  d_2010_selected,
  d_2014_selected ) %>%
  mutate( survey_year = as.factor( survey_year ) )

summary( pre2021 )

# check for overlapping participants across SPHC-B 2002 to 2014
# unable to check for SPHC-B 2021, because of its independent lopnr number system
length( intersect( d_2002_selected$lopnr, d_2006_selected$lopnr ) ) # 999 individuals participated in both SPHC-B 2002 and 2006
length( intersect( d_2002_selected$lopnr, d_2010_selected$lopnr ) ) # 0
length( intersect( d_2002_selected$lopnr, d_2014_selected$lopnr ) ) # 62
length( intersect( d_2006_selected$lopnr, d_2010_selected$lopnr ) ) # 0
length( intersect( d_2006_selected$lopnr, d_2014_selected$lopnr ) ) # 83
length( intersect( d_2010_selected$lopnr, d_2014_selected$lopnr ) ) # 0
length( Reduce( intersect, list( d_2002_selected$lopnr, d_2006_selected$lopnr, d_2014_selected$lopnr ) ) ) # two individuals participated in SPHC-B 2002, 2006, and 2014

pre2021_selected <- pre2021 %>%
  mutate( survey_year = fct_rev( survey_year ) ) %>%
  arrange( lopnr, survey_year ) %>%
  distinct( lopnr, .keep_all = TRUE ) # remove duplicates and retain data for the latest year
sum( duplicated( pre2021_selected$lopnr ) ) # 0
nrow( pre2021_selected ) # 110,353
summary( pre2021_selected )

# define variables
pre2021_selected <- pre2021_selected %>%
  mutate(
    
    # sexual identity
    sexual_identity_baseline = case_when(
      survey_year %in% c( "SPHC 2002", "SPHC 2006" ) ~ sexual_identity_2010,
      survey_year == "SPHC 2010" ~ sexual_identity_2010,
      survey_year == "SPHC 2014" ~ sexual_identity_2014 ),
    
    # generation
    generation = factor(
      
      case_when(
        birth_year >= 1997 & birth_year <= 2012 ~ "Generation Z (1997–2012)",
        birth_year >= 1981 & birth_year <= 1996 ~ "Millennials (1981–1996)",
        birth_year >= 1965 & birth_year <= 1980 ~ "Generation X (1965–1980)",
        birth_year >= 1946 & birth_year <= 1964 ~ "Baby Boomers (1946–1964)",
        birth_year >= 1928 & birth_year <= 1945 ~ "Silent Generation (1928–1945)",
        birth_year >= 1901 & birth_year <= 1927 ~ "Greatest Generation (1901–1927)" ), 
      
      levels = c( "Generation Z (1997–2012)", "Millennials (1981–1996)", "Generation X (1965–1980)", "Baby Boomers (1946–1964)", "Silent Generation (1928–1945)", "Greatest Generation (1901–1927)" ) ) )

table( pre2021_selected$survey_year, pre2021_selected$sexual_identity_baseline, useNA = "always" )
summary( pre2021_selected )


### SPHC 2021 ###

d_2021_selected <- d_2021 %>%
  select( any_of( variable_list ) ) %>%
  rename( sexual_identity_baseline = sexual_identity_2021 ) %>%
  mutate( 
    
    survey_year = "SPHC 2021",
          
    # generation
    generation = factor(
      
      case_when(
        birth_year >= 1997 & birth_year <= 2012 ~ "Generation Z (1997–2012)",
        birth_year >= 1981 & birth_year <= 1996 ~ "Millennials (1981–1996)",
        birth_year >= 1965 & birth_year <= 1980 ~ "Generation X (1965–1980)",
        birth_year >= 1946 & birth_year <= 1964 ~ "Baby Boomers (1946–1964)",
        birth_year >= 1928 & birth_year <= 1945 ~ "Silent Generation (1928–1945)",
        birth_year >= 1901 & birth_year <= 1927 ~ "Greatest Generation (1901–1927)" ), 
      
      levels = c( "Generation Z (1997–2012)", "Millennials (1981–1996)", "Generation X (1965–1980)", "Baby Boomers (1946–1964)", "Silent Generation (1928–1945)", "Greatest Generation (1901–1927)" ) ) )

summary( d_2021_selected )
sum( duplicated( d_2021_selected$lopnr ) ) # 0
table( d_2021_selected$sexual_identity_baseline, useNA = "always" )
nrow( d_2021_selected ) # 23,066
```

### 4. Determine Follow-Up Period Through Registry
```{r}
### SPHC 2002 to 2014 ###

# all migration dates
migration_date_2002_2014 <- read_sas('/Volumes/LGBT Project data/Swedish Registers/migration_all.sas7bdat')
summary( migration_date_2002_2014 )
table( migration_date_2002_2014$Posttyp, useNA = "always" )

migration_date_2002_2014 <- migration_date_2002_2014 %>%
  rename( date = migrationdate, event_type = Posttyp ) %>%
  mutate( event_type = as.factor( recode( event_type,
                                          "Inv" = "move-in",
                                          "Utv" = "move-out" ) ) )
summary( migration_date_2002_2014 )
length( unique( migration_date_2002_2014$lopnr ) ) # 12,409 had any moving-in and/or moving-out between 1990 and 2021
length( intersect( unique( migration_date_2002_2014$lopnr ), pre2021_selected$lopnr ) ) # 12,409

nrow(
  migration_date_2002_2014 %>%
    arrange( lopnr, date ) %>%              
    group_by( lopnr ) %>%                      
    slice( 1 ) %>%                            
    ungroup() %>%
    filter( event_type == "move-in" ) ) # 8,129 had move-in as the first event

nrow(
  migration_date_2002_2014 %>%
    arrange( lopnr, date ) %>%
    group_by( lopnr ) %>%
    slice_tail( n = 1 ) %>%
    ungroup() %>%
    filter( event_type == "move-out" ) ) # 1,578 had move-out as the last event

# all death dates
date_2002_2014 <- read_sas('/Volumes/LGBT Project data/Swedish Registers/dates_2002_2014.sas7bdat')
summary( date_2002_2014 )
length( unique( date_2002_2014$lopnr ) ) # 15,117
length( unique( date_2002_2014$lopnr ) ) == nrow( date_2002_2014 ) # TRUE
length( intersect( unique( date_2002_2014$lopnr ), pre2021_selected$lopnr ) ) # 15,117

date_2002_2014 %>%
  filter( death_date != "" ) %>%
  mutate( lengths = nchar( death_date ) ) %>%
  count( lengths )

death_date_2002_2014 <- date_2002_2014 %>%
  select( "lopnr", "death_date" ) %>%
  filter( death_date != "" ) %>%
  mutate( death_date = as.Date( death_date, format = "%Y%m%d" ),
          event_type = "death" ) %>%
  rename( date = death_date )
summary( death_date_2002_2014 )
length( unique( death_date_2002_2014$lopnr ) ) # 8,614
length( unique( death_date_2002_2014$lopnr ) ) == nrow( death_date_2002_2014 ) # TRUE
length( intersect( unique( death_date_2002_2014$lopnr ), pre2021_selected$lopnr ) ) # 8,614

# merge migration dates and death dates
dates_all_2002_2014 <- bind_rows( migration_date_2002_2014, death_date_2002_2014 ) %>%
  mutate( event_type = factor( event_type, levels = c( "move-in", "move-out", "death" ) ) ) %>%
  arrange( lopnr, date )
summary( dates_all_2002_2014 )
length( unique( dates_all_2002_2014$lopnr ) ) # 20,831
length( intersect( unique( dates_all_2002_2014$lopnr ), pre2021_selected$lopnr ) ) # 20,831

dates_all_2002_2014 <- dates_all_2002_2014 %>%
  left_join( pre2021_selected %>% select( "lopnr", "birth_year", "survey_year" ), by = "lopnr" ) %>%
  mutate( survey_year = fct_rev( survey_year ),
          event_age = year( date ) - birth_year )
summary( dates_all_2002_2014 )

# visualize age at death
ggplot( dates_all_2002_2014 %>% filter( event_type == "death" ), 
        aes( x = event_age ) ) +
  geom_histogram( binwidth = 5, fill = "steelblue", color = "white" ) +
  labs( x = "Age at Death",
        y = "Number of Individuals" ) +
  theme_minimal() +
  facet_wrap( ~ survey_year,
              scales = "free" )

# check if there are duplicate events
id_with_duplicate_events <- dates_all_2002_2014 %>%
  arrange( lopnr, date ) %>%
  group_by( lopnr ) %>%
  mutate(
    next_event = lead( event_type ),
    same_as_next = event_type == next_event ) %>%
  filter( same_as_next == TRUE ) %>%
  pull( lopnr ) %>%
  unique() # 6

#View(
#  dates_all_2002_2014 %>%
#  filter( lopnr %in% id_with_duplicate_events ) %>%
#  arrange( lopnr, date ) 
#  )

dates_all_2002_2014_cleaned <- dates_all_2002_2014 %>%
  arrange( lopnr, date ) %>%
  group_by( lopnr ) %>%
  filter( event_type != lag( event_type ) | is.na( lag( event_type ) ) ) %>% # arbitrarily exclude the second duplicate event
  ungroup()

#View( dates_all_2002_2014_cleaned %>% filter( lopnr %in% id_with_duplicate_events ) )

# check if there is any event after death
ids_with_death <- dates_all_2002_2014_cleaned %>%
  filter( event_type == "death" ) %>%
  pull( lopnr ) %>%
  unique()

dates_all_2002_2014_cleaned %>%
  filter( lopnr %in% ids_with_death ) %>%
  arrange( lopnr, date ) %>%
  group_by( lopnr ) %>%
  mutate( death_date = min( date[ event_type == "death" ] ) ) %>%
  ungroup() %>%
  filter( date > death_date ) # 0

# check for duplicate event-date combinations
dates_all_2002_2014_cleaned %>%
  count( lopnr, event_type, date ) %>%
  filter( n > 1 ) # 0

# check duration between events
dates_all_2002_2014_cleaned %>%
  arrange( lopnr, date ) %>%            
  group_by( lopnr ) %>%                   
  mutate(
    next_event = lead( event_type ),
    next_date = lead( date ),
    duration = as.numeric( difftime( next_date, date, units = "days" ) ) ) %>%
  ungroup() %>%
  select( next_event, next_date, duration ) %>%
  summary()

# prepare for plotting
dates_all_2002_2014_cleaned <- dates_all_2002_2014_cleaned %>%
  group_by( survey_year ) %>%
  mutate( individual_id = dense_rank( lopnr ) ) %>% # generate continuous pseudo ID number
  ungroup()
summary( dates_all_2002_2014_cleaned )

length( unique( dates_all_2002_2014_cleaned[ dates_all_2002_2014_cleaned$survey_year == "SPHC 2002", ]$lopnr ) ) # 5,503 in SPHC 2002
max( dates_all_2002_2014_cleaned[ dates_all_2002_2014_cleaned$survey_year == "SPHC 2002", ]$individual_id )
length( unique( dates_all_2002_2014_cleaned[ dates_all_2002_2014_cleaned$survey_year == "SPHC 2006", ]$lopnr ) ) # 6,938 in SPHC 2006
max( dates_all_2002_2014_cleaned[ dates_all_2002_2014_cleaned$survey_year == "SPHC 2006", ]$individual_id )
length( unique( dates_all_2002_2014_cleaned[ dates_all_2002_2014_cleaned$survey_year == "SPHC 2010", ]$lopnr ) ) # 5,208 in SPHC 2010
max( dates_all_2002_2014_cleaned[ dates_all_2002_2014_cleaned$survey_year == "SPHC 2010", ]$individual_id )
length( unique( dates_all_2002_2014_cleaned[ dates_all_2002_2014_cleaned$survey_year == "SPHC 2014", ]$lopnr ) ) # 3,182 in SPHC 2014
max( dates_all_2002_2014_cleaned[ dates_all_2002_2014_cleaned$survey_year == "SPHC 2014", ]$individual_id )


# plotting
sampling_lines <- data.frame(
  survey_year = c( "SPHC 2002", "SPHC 2006", "SPHC 2010", "SPHC 2014" ),
  x = as.Date( c( "2007-02-28", "2006-08-09", "2009-12-31", "2014-08-31" ) ),
  yend = c( 5503 + 40, 6938 + 40, 5208 + 40, 3182 + 40 )
  )

# check for exact date matches per survey year
dates_all_2002_2014_cleaned %>%
  left_join( sampling_lines %>% select( survey_year, x ), by = "survey_year" ) %>%
  filter( date == x ) # 0

p1_follow_up_2002_2014 <- 
  ggplot( dates_all_2002_2014_cleaned,
          aes( x = date, y = individual_id, color = event_type ) ) +
  
  geom_point( size = 1.5 ) +
  
  geom_segment(
    data = sampling_lines,
    aes( x = x, xend = x, y = -Inf, yend = yend ),
    inherit.aes = FALSE,
    linetype = "dashed",
    color = "grey20",
    linewidth = 0.5
    ) +
  
  scale_color_manual(
    values = c( "move-in" = "green", "move-out" = "blue", "death" = "red" ),
    labels = c( "move-in" = "Move to Sweden", "move-out" = "Move outside Sweden", "death" = "Death" ) ) +

  scale_x_date(
    limits = as.Date( c( "1990-01-01", NA ) ),
    breaks = seq( as.Date( "1990-01-01" ), as.Date( "2022-01-01" ), by = "2 years" ),
    date_labels = "%Y",
    expand = c( 0.02, 0 ) ) +
  
  labs( x = "Calendar Year", y = "Individual Pseudo ID Number" ) +
  
  theme_classic() +
  theme(
    axis.text.x = element_text( angle = 45, hjust = 1, family = "Arial", size = 11 ),
    axis.text.y = element_text( family = "Arial", size = 11 ),
    axis.title = element_text( family = "Arial", size = 12 ),
    axis.line.y = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text( family = "Arial", size = 12, margin = margin( b = 5 ) ),
    panel.spacing = unit( 1.5, "lines" ),
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text( family = "Arial", size = 11 ) ) +
  
  facet_wrap( ~ survey_year,
              scales = "free",
              labeller = labeller(
                survey_year = c(
                  "SPHC 2002" = "SPHC 2002 (N = 5,503)",
                  "SPHC 2006" = "SPHC 2006 (N = 6,938)",
                  "SPHC 2010" = "SPHC 2010 (N = 5,208)",
                  "SPHC 2014" = "SPHC 2014 (N = 3,182)" ) ) 
              ) +
  
  ggh4x::facetted_pos_scales( y = list(
    survey_year == "SPHC 2002" ~ scale_y_continuous( expand = c( 0.02, 0 ), breaks = c( 1, 1000, 3000, 5000 ) ),
    survey_year == "SPHC 2006" ~ scale_y_continuous( expand = c( 0.02, 0 ), breaks = c( 1, 1000, 3000, 5000, 7000 ) ),
    survey_year == "SPHC 2010" ~ scale_y_continuous( expand = c( 0.02, 0 ), breaks = c( 1, 1000, 3000, 5000 ) ),
    survey_year == "SPHC 2014" ~ scale_y_continuous( expand = c( 0.02, 0 ), breaks = c( 1, 1000, 2000, 3000 ) ) ) )

p1_follow_up_2002_2014
# ggsave( "Draft plots/registry_follow_up_2002_2014_(1).png", plot = p1_follow_up_2002_2014, width = 15, height = 9, dpi = 600 )


# identify those whose first event is move-out or death
start_with_exit <- dates_all_2002_2014_cleaned %>%
  arrange( lopnr, date ) %>%
  group_by( lopnr ) %>%
  slice( 1 ) %>%
  filter( event_type %in% c( "move-out", "death" ) ) %>%
  pull( lopnr )

summary( dates_all_2002_2014_cleaned %>% filter( lopnr %in% start_with_exit ) )

artificial_entries <- tibble(
  lopnr = start_with_exit,
  event_type = "move-in-artificial",
  date = as.Date( "1990-01-01" ) )

# identify those whose last event is move-in
end_with_entry <- dates_all_2002_2014_cleaned %>%
  arrange( lopnr, date ) %>%
  group_by( lopnr ) %>%
  slice_tail( n = 1 ) %>%
  filter( event_type == "move-in" ) %>%
  pull( lopnr )

summary( dates_all_2002_2014_cleaned %>% filter( lopnr %in% end_with_entry ) )

artificial_exits <- tibble(
  lopnr = end_with_entry,
  event_type = "move-out-artificial",
  date = as.Date( "2021-12-31" ) )

dates_all_2002_2014_complete <- bind_rows( artificial_entries, 
                                           artificial_exits,
                                           dates_all_2002_2014_cleaned %>% select( "lopnr", "event_type", "date" ) ) %>%
  left_join( pre2021_selected %>% 
               select( "lopnr", "birth_year", "sex", "country_of_birth", "survey_year", "sexual_identity_baseline", "generation" ), by = "lopnr" ) %>%
  mutate( event_type = as.factor( event_type ),
          survey_year = fct_rev( survey_year ) ) %>%
  arrange( lopnr, date )

summary( dates_all_2002_2014_complete )
dates_all_2002_2014_complete %>%
  distinct( survey_year, lopnr ) %>%
  count( survey_year, name = "n_unique_individuals" )

follow_up_intervals <- dates_all_2002_2014_complete %>%
  arrange( lopnr, date ) %>%
  group_by( lopnr ) %>%
  mutate(
    next_date = lead( date ),
    next_event = lead( event_type ),
    y_pos = as.numeric( factor( lopnr ) )
  ) %>%
  filter( event_type %in% c( "move-in", "move-in-artificial" ) ) %>%
  ungroup()

summary( follow_up_intervals )

p2_follow_up_2002_2014 <-
  ggplot( follow_up_intervals_plot[ 1:1000, ], 
        aes( x = date, xend = next_date, y = y_pos, yend = y_pos ) ) +
  geom_segment( color = "steelblue", linewidth = 0.5 ) +
  scale_y_continuous( breaks = NULL ) +
  labs(
    x = "Date",
    y = "Individuals"  ) +
  facet_wrap( ~ survey_year, scales = "free_y" ) +
  theme_minimal() +
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid.major.y = element_blank()
  )

  
  ggplot( dates_all_2002_2014_cleaned,
          aes( x = date, y = individual_id, color = event_type ) ) +
  
  geom_point( size = 1.5 ) +
  
  geom_segment(
    data = sampling_lines,
    aes( x = x, xend = x, y = -Inf, yend = yend ),
    inherit.aes = FALSE,
    linetype = "dashed",
    color = "grey20",
    linewidth = 0.5
    ) +
  
  scale_color_manual(
    values = c( "move-in" = "green", "move-out" = "blue", "death" = "red" ),
    labels = c( "move-in" = "Move to Sweden", "move-out" = "Move outside Sweden", "death" = "Death" ) ) +

  scale_x_date(
    limits = as.Date( c( "1990-01-01", NA ) ),
    breaks = seq( as.Date( "1990-01-01" ), as.Date( "2022-01-01" ), by = "2 years" ),
    date_labels = "%Y",
    expand = c( 0.02, 0 ) ) +
  
  labs( x = "Calendar Year", y = "Individual Pseudo ID Number" ) +
  
  theme_classic() +
  theme(
    axis.text.x = element_text( angle = 45, hjust = 1, family = "Arial", size = 11 ),
    axis.text.y = element_text( family = "Arial", size = 11 ),
    axis.title = element_text( family = "Arial", size = 12 ),
    axis.line.y = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text( family = "Arial", size = 12, margin = margin( b = 5 ) ),
    panel.spacing = unit( 1.5, "lines" ),
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text( family = "Arial", size = 11 ) ) +
  
  facet_wrap( ~ survey_year,
              scales = "free",
              labeller = labeller(
                survey_year = c(
                  "SPHC 2002" = "SPHC 2002 (N = 5,503)",
                  "SPHC 2006" = "SPHC 2006 (N = 6,938)",
                  "SPHC 2010" = "SPHC 2010 (N = 5,208)",
                  "SPHC 2014" = "SPHC 2014 (N = 3,182)" ) ) 
              ) +
  
  ggh4x::facetted_pos_scales( y = list(
    survey_year == "SPHC 2002" ~ scale_y_continuous( expand = c( 0.02, 0 ), breaks = c( 1, 1000, 3000, 5000 ) ),
    survey_year == "SPHC 2006" ~ scale_y_continuous( expand = c( 0.02, 0 ), breaks = c( 1, 1000, 3000, 5000, 7000 ) ),
    survey_year == "SPHC 2010" ~ scale_y_continuous( expand = c( 0.02, 0 ), breaks = c( 1, 1000, 3000, 5000 ) ),
    survey_year == "SPHC 2014" ~ scale_y_continuous( expand = c( 0.02, 0 ), breaks = c( 1, 1000, 2000, 3000 ) ) ) )

p2_follow_up_2002_2014
# ggsave( "Draft plots/registry_follow_up_2002_2014_(2).png", plot = p2_follow_up_2002_2014, width = 15, height = 9, dpi = 600 )
```

### 5. Registry-Based Health Outcomes
#### 5.1. Complete-case analysis
```{r}
### SPHC 2002 to 2014 ###

# use of antidepressants and anxiolytics
atc_2002_2014_original <- read_sas('/Volumes/LGBT Project data/Swedish Registers/atc_2002_2014.sas7bdat') %>%
  filter( !grepl( "^N05CD", ATC ) ) # include participants who had at least one dispensed prescription of N05B or N06A from 2005-06-30 to 2021-12-31

# check variables
summary( atc_2002_2014_original )
length( unique( atc_2002_2014_original$lopnr ) ) # 44,963 individuals had any dispensed prescription
unique( atc_2002_2014_original$ATC )
length( intersect( atc_2002_2014_original$lopnr, pre2021_selected$lopnr ) ) # 44,963
length( intersect( atc_2002_2014_original$lopnr, dates_all_2002_2014$lopnr ) ) # 9,519

atc_2002_2014 <- atc_2002_2014_original %>%
  select( "lopnr", "ATC", "EDATUM" ) %>%
  mutate( 
    drug_class = as.factor( 
      case_when(
        grepl( "^N06A", ATC ) ~ "N06A",
        grepl( "^N05B", ATC ) ~ "N05B" ) ),
    year = year( EDATUM ) )

summary( atc_2002_2014 )
length( unique( atc_2002_2014$lopnr ) ) # 44,963

# prepare and merge datasets
atc_2002_2014_summary <- atc_2002_2014 %>%
  group_by( lopnr, drug_class, year ) %>%
  summarise( prescription_count = n(), .groups = "drop" ) %>%
  pivot_wider(
    names_from = drug_class,
    values_from = prescription_count,
    names_prefix = "prescription_count_",
    values_fill = 0
  ) %>%
  mutate( 
    use_N06A = as.factor( ifelse( prescription_count_N06A > 0, "Yes", "No" ) ),
    use_N05B = as.factor( ifelse( prescription_count_N05B > 0, "Yes", "No" ) ) )
summary( atc_2002_2014_summary )

all_combos <- expand.grid(
  lopnr = unique( pre2021_selected$lopnr ),
  year = 2005:2021
  )

all_combos <- as_tibble( all_combos ) %>%
  left_join( pre2021_selected %>% select( lopnr, sexual_identity_baseline, generation, birth_year ), by = "lopnr" ) %>%
  mutate( age_in_year = year - birth_year ) %>%
  filter( age_in_year >= 12 )

atc_2002_2014_summary_cc <- all_combos %>%
  left_join( atc_2002_2014_summary, by = c( "lopnr", "year" ) ) %>%
  mutate( 
    prescription_count_N06A = replace_na( prescription_count_N06A, 0 ),
    prescription_count_N05B = replace_na( prescription_count_N05B, 0 ),
    use_N06A = replace_na( use_N06A, "No" ),
    use_N05B = replace_na( use_N05B, "No" ) )

str( atc_2002_2014_summary_cc )


summary_data <- atc_2002_2014_summary_cc %>%
  group_by(year, generation, sexual_identity_baseline) %>%
  summarise(
    prevalence_N06A = mean(use_N06A == "Yes", na.rm = TRUE),
    prevalence_N05B = mean(use_N05B == "Yes", na.rm = TRUE),
    n = n(),
    .groups = "drop"
  ) %>%
  filter(
    sexual_identity_baseline %in% c("Heterosexual", "Homosexual", "Bisexual")
  )

ggplot(summary_data, aes(x = year)) +
  geom_line(aes(y = prevalence_N06A, color = sexual_identity_baseline), size = 1) +
  geom_line(aes(y = prevalence_N05B, color = sexual_identity_baseline), linetype = "dashed", size = 1) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    x = "Year",
    y = "Prevalence (solid = N06A, dashed = N05B)",
    color = "Sexual Identity",
    title = "Yearly Prevalence of Antidepressants (N06A) and Anxiolytics (N05B) by Generation"
  ) +
  facet_wrap(~ generation) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    strip.text = element_text(face = "bold")
  )

mean_summary <- atc_2002_2014_summary_cc %>%
  filter(sexual_identity_baseline %in% c("Heterosexual", "Homosexual", "Bisexual")) %>%
  group_by(year, generation, sexual_identity_baseline) %>%
  summarise(
    mean_N06A = mean(prescription_count_N06A, na.rm = TRUE),
    mean_N05B = mean(prescription_count_N05B, na.rm = TRUE),
    .groups = "drop"
  )

ggplot(mean_summary, aes(x = year)) +
  geom_line(aes(y = mean_N06A, color = sexual_identity_baseline), size = 1) +
  geom_line(aes(y = mean_N05B, color = sexual_identity_baseline), linetype = "dashed", size = 1) +
  labs(
    x = "Year",
    y = "Mean Number of Prescriptions (solid = N06A, dashed = N05B)",
    color = "Sexual Identity",
    title = "Mean Number of Prescriptions by Generation and Sexual Identity"
  ) +
  facet_wrap(~ generation) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    strip.text = element_text(face = "bold")
  )




# cross check data
summary( d_2010_complete$prescription_count_2010_N06A )
sum( d_2010_complete$prescription_count_2010_N06A, na.rm = TRUE )
sum( atc_2010_summary_wide$prescription_count_2010_N06A )
summary( d_2010_complete$prescription_count_2010_N05B )
sum( d_2010_complete$prescription_count_2010_N05B, na.rm = TRUE )
sum( atc_2010_summary_wide$prescription_count_2010_N05B )
table( d_2010_complete$prescribed_2010_N06A, useNA = "always" )
table( atc_2010_summary_wide$prescribed_2010_N06A, useNA = "always" )
table( d_2010_complete$prescribed_2010_N05B, useNA = "always" )
table( atc_2010_summary_wide$prescribed_2010_N05B, useNA = "always" )



atc_2002_2014 <- read_sas('/Volumes/LGBT Project data/Swedish Registers/atc_2002_2014.sas7bdat') %>%
  filter( !grepl( "^N05CD", ATC ) ) # include participants who had at least one dispensed prescription of N05B or N06A from 2005-06-30 to 2021-12-31

# check each variable
summary( atc_2002_2014 )
length( unique( atc_2002_2014$lopnr ) ) # 44,963 individuals had any dispensed prescription
length( intersect( atc_2002_2014$lopnr, pre2021_selected$lopnr ) )
unique( atc_2002_2014$ATC )
nrow( atc_2002_2014 %>% filter( ANTAL <= 0 & !is.na( ANTAL ) ) ) # 1,700 rows had a value of <= 0 in ANTAL
summary( atc_2002_2014 %>% filter( !is.na( dddforp ) ) ) # earliest date of dispensed prescription is 2010-02-05
table( atc_2002_2014$lan, useNA = "always" )

atc_2002_2014 <- atc_2002_2014 %>%
  mutate(
    drug_class = case_when(
      grepl( "^N06A", ATC ) ~ "N06A",
      grepl( "^N05B", ATC ) ~ "N05B" ),
    year = year( EDATUM ) )

table( atc_2002_2014$drug_class, useNA = "always" )
summary( atc_2002_2014$year )

atc_summary_by_year <- atc_2002_2014 %>%
  group_by( lopnr, drug_class, year ) %>%
  summarise( prescription_count = n(), .groups = "drop" )

# Define all possible combinations
all_combinations <- expand.grid(
  lopnr = unique(pre2021_selected$lopnr),
  year = 2005:2014,
  drug_class = c("N05B", "N06A")
)

# Join with person-level data
full_data <- all_combinations %>%
  left_join(d_pooled_cohort %>% filter( survey_year != "SPHC 2021" ), by = "lopnr") %>%
  left_join(atc_2002_2014 %>%
              group_by(lopnr, year, drug_class) %>%
              summarise(prescription_count = n(), .groups = "drop"),
            by = c("lopnr", "year", "drug_class")) %>%
  mutate(
    prescription_count = ifelse(is.na(prescription_count), 0, prescription_count),
    has_prescription = ifelse(prescription_count > 0, 1, 0)
  )

prevalence_data_by_year <- d_pooled_cohort %>%
  filter( survey_year != "SPHC 2021" ) %>%
  left_join( atc_summary_by_year, by = "lopnr" ) %>%
  mutate(
    prescription_count = ifelse( is.na( prescription_count ), 0, prescription_count ),
    has_prescription = ifelse( prescription_count > 0, 1, 0 )
    )

ggplot(
  full_data %>% 
    filter(!is.na(sexual_identity_baseline), !is.na(drug_class)),
  aes(x = year, y = prescription_count, color = sexual_identity_baseline)
) +
  stat_summary(fun = mean, geom = "line", linewidth = 1) +
  facet_wrap(~ drug_class, scales = "free_y") +
  labs(
    x = "Year", y = "Avg. Number of Prescriptions",
    color = "Sexual Identity"
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom",
    axis.text = element_text(size = 11, family = "Arial"),
    strip.text = element_text(size = 12, family = "Arial")
  )
```

```{r}
### SPHC 2021 ###

atc_2021 <- read_sas('/Volumes/LGBT Project data/Swedish Registers/atc_2021.sas7bdat') %>%
  filter( !grepl( "^N05CD", ATC ) ) %>%
  rename( lopnr = lopnr2 )
  
# check each variable
summary( atc_2021 )
length( unique( atc_2021$lopnr ) ) # 7,505 individuals had any dispensed prescription
length( intersect( atc_2021$lopnr, d_2021_selected$lopnr ) )
unique( atc_2021$ATC )
```

```{r}

atc_summary <- atc_2002_2014 %>%
  group_by( lopnr, drug_class ) %>%
  summarise( prescription_count = n(), .groups = "drop" )

prevalence_data <- pre2021_selected %>%
  select(lopnr, age_baseline, sex, survey_year, country_of_birth) %>%
  left_join(atc_summary, by = "lopnr") %>%
  mutate(
    prescription_count = ifelse(is.na(prescription_count), 0, prescription_count),
    has_prescription = ifelse(prescription_count > 0, 1, 0)
  )



d_pdr_regitry <- d_pdr_regitry %>%
  mutate(
    presence_N06A = factor( if_else( grepl( "N06A", ATC ), "Yes", "No" ), levels = c( "Yes", "No" ) ),
    presence_N05B = factor( if_else( grepl( "N05B", ATC ), "Yes", "No" ), levels = c( "Yes", "No" ) ),
    year = year( EDATUM )
    )

summary( d_pdr_regitry )
sum( d_pdr_regitry$dose, na.rm = TRUE )
sum( d_pdr_regitry$ddd_N06A, na.rm = TRUE ) + sum( d_pdr_regitry$ddd_N05B, na.rm = TRUE ) # all numbers match

count_ATC <- d_pdr_regitry %>%
  group_by( lopnr, year ) %>%
  summarise(
    prescription_N06A = sum( presence_N06A == "Yes" ),
    prescription_N05B = sum( presence_N05B == "Yes" ),
    ddd_N06A = if_else( all( is.na( ddd_N06A ) ), NA, sum( ddd_N06A, na.rm = TRUE ) ),
    ddd_N05B = if_else( all( is.na( ddd_N05B ) ), NA, sum( ddd_N05B, na.rm = TRUE ) ),
    .groups = "drop"
  ) # calculate no. of prescriptions and DDD per year

summary( count_ATC )
sum( count_ATC$prescription_N06A )
sum( count_ATC$prescription_N05B )
table( d_pdr_regitry$presence_N06A )
table( d_pdr_regitry$presence_N05B )
sum( count_ATC$ddd_N06A, na.rm = TRUE )
sum( count_ATC$ddd_N05B, na.rm = TRUE )
sum( d_pdr_regitry$ddd_N06A, na.rm = TRUE )
sum( d_pdr_regitry$ddd_N05B, na.rm = TRUE ) # all numbers match

count_ATC_wide <- count_ATC %>%
  # transform to wide format
  pivot_wider( 
    names_from = year, 
    values_from = c( prescription_N06A, prescription_N05B, ddd_N06A, ddd_N05B ),
    names_sep = "_",
    values_fill = 0 # NOTE: assume that among participants who HAD at least one prescription record during 2005-2021, those who did not have any prescription during a specific year did not receive a prescription during that year, i.e., assume complete follow-up during 2005-2021 through register
    )
n_miss( count_ATC_wide ) # 37 missing
miss_var_summary( count_ATC_wide )
count_ATC_wide <- count_ATC_wide %>%
  mutate( across( starts_with( "ddd_N06A" ) | starts_with( "ddd_N05B" ), ~ ifelse( is.na(.), 100000, . ) ) )

d_2010_complete_merged <- left_join( d_2010_complete, count_ATC_wide, by = "lopnr" )
inner_join( d_2010_complete, count_ATC_wide, by = "lopnr" ) %>% 
  summarize( count = n() ) # 12,646 matched

d_2010_complete_merged_cleaned <- d_2010_complete_merged %>%
  mutate( 
    across( contains( c( "N06A", "N05B" ) ), 
                  ~ ifelse( is.na( lopnr ), ., 
                            ifelse( is.na(.), 0, . ) ) ), # NOTE: assume that among participants who did NOT have any prescription record during 2005-2021, they did not receive a prescription during the period, i.e., assume complete follow-up during 2005-2021 through register
    
    # create new columns
    across(
      starts_with( "prescription_N06A_" ),
      ~ ifelse(. > 0, "Yes", "No" ),
      .names = "presence_N06A_{str_sub(.col, -4)}"
      ),
    
    across(
      starts_with( "prescription_N05B_" ),
      ~ ifelse(. > 0, "Yes", "No" ),
      .names = "presence_N05B_{str_sub(.col, -4)}"
      )
    )

d_2010_complete_merged_cleaned <- d_2010_complete_merged_cleaned %>%
  mutate( across( starts_with( "ddd_N06A" ) | starts_with( "ddd_N05B" ), ~ ifelse(. == 100000, NA, .) ) )
summary( d_2010_complete_merged_cleaned[ , c( 79:180 ) ] )

# in summary, the final merged dataset assumes that all participants have complete follow-up through register from 2005 to 2021; therefore, those who do not have any prescription record are assumed not to have any prescription


str( immigration_date )
unique( nchar( immigration_date$first_immigration_date ) )
immigration_date <- immigration_date %>%
  mutate( first_immigration_date = ymd( first_immigration_date ) )
summary( immigration_date )

d_2010_complete_combined <- left_join( d_2010_complete, immigration_date, by = "lopnr" )
summary( d_2010_complete_combined$first_immigration_date )
inner_join( d_2010_complete, immigration_date, by = "lopnr" ) %>% 
  summarize( count = n() ) # 2,500 immigrated to Sweden
table( d_2010_complete_combined[ !is.na( d_2010_complete_combined$first_immigration_date ), ]$country_of_birth  )
table( d_2010_complete_combined[ is.na( d_2010_complete_combined$first_immigration_date ), ]$country_of_birth, useNA = "always"  )

d_2010_complete_combined <- d_2010_complete_combined %>%
  mutate( start_date_pdr = case_when(
    !is.na( first_immigration_date ) ~ first_immigration_date,
    is.na( first_immigration_date) & !is.na( lopnr ) ~ ymd( "20050630" ),
    TRUE ~ NA
    ) )
summary( d_2010_complete_combined$start_date_pdr )
```


