---
title: "Sexual identity and health outcomes in Stockholm County, SPHC-B 2021"
author: Willi Zhang
email: willi.zhang@ki.se
output: html_notebook
editor_options: 
  chunk_output_type: console
---

### 1. Load Packages
```{r}
library(haven)
library(tidyr)
library(tidyverse)
library(dplyr)
library(finalfit)
library(stringr)
library(ggplot2)
library(naniar)
library(jomo)
library(mitml)
library(mitools)
library(survey)
library(svyVGAM)
library(vcd)
library(rcompanion)
source('Helper_functions.R') # helper function
```

### 2. Import and Prepare Data
```{r}
load('/Volumes/LGBT Project data/d_2021.RData')

# sampling strata
n_miss( d_2021$stratum )
d_2021$sampling_strata <- as.factor( d_2021$stratum )
length( unique( d_2021$sampling_strata ) ) # 38 strata

d_2021 <- d_2021 %>%
  mutate( sampling_strata_region = recode( sampling_strata, 
                                           `114` = "Upplands-Väsby",
                                           `115` = "Vallentuna",
                                           `117` = "Österåker",
                                           `120` = "Värmdö",
                                           `123` = "Järfälla",
                                           `125` = "Ekerö",
                                           `126` = "Huddinge",
                                           `127` = "Botkyrka",
                                           `128` = "Salem",
                                           `136` = "Haninge",
                                           `138` = "Tyresö",
                                           `139` = "Upplands-Bro",
                                           `140` = "Nykvarn",
                                           `160` = "Täby",
                                           `162` = "Danderyd",
                                           `163` = "Sollentuna",
                                           `181` = "Södertälje",
                                           `182` = "Nacka",
                                           `183` = "Sundbyberg",
                                           `184` = "Solna",
                                           `186` = "Lidingö",
                                           `187` = "Vaxholm",
                                           `188` = "Norrtälje",
                                           `191` = "Sigtuna",
                                           `192` = "Nynäshamn",
                                           `180103` = "Spånga-Tensta",
                                           `180104` = "Hässelby-Vällingby",
                                           `180106` = "Bromma",
                                           `180108` = "Kungsholmen",
                                           `180109` = "Norrmalm",
                                           `180110` = "Östermalm",
                                           `180115` = "Skarpnäck",
                                           `180118` = "Farsta",
                                           `180124` = "Skärholmen",
                                           `180125` = "Rinkeby-Kista",
                                           `180127` = "Södermalm",
                                           `180128` = "Enskede-Årsta-Vantör",
                                           `180129` = "Hägersten-Älvsjö"
                                           ) )

# sexual identity
table( d_2021$F21F45_Q57, useNA = "always" )
d_2021$sexual_identity_2021 <- factor( ifelse( d_2021$F21F45_Q57 == 1, "Heterosexual", 
                                          ifelse( d_2021$F21F45_Q57 == 2, "Homosexual",
                                                  ifelse( d_2021$F21F45_Q57 == 3, "Bisexual", "None of the above" ) ) ),
                                  levels = c( "Heterosexual", "Homosexual", "Bisexual", "None of the above" ) )
table( d_2021$sexual_identity_2021, useNA = "always" )

# sex
table( d_2021$kon, useNA = "always" )
d_2021$sex <- factor( ifelse( d_2021$kon == 1, "Male", "Female" ), 
                      levels = c( "Male", "Female" ) )
table( d_2021$sex, useNA = "always" )

# age
summary( d_2021$F21alder )
d_2021$age <- d_2021$F21alder
d_2021$age_cat <- factor( ifelse( d_2021$age <= 29, "16-29", 
                                  ifelse( d_2021$age >=30 & d_2021$age <= 44, "30-44",
                                          ifelse( d_2021$age >= 45 & d_2021$age <= 59, "45-59", ">=60" ) ) ),
                          levels = c( "16-29", "30-44", "45-59", ">=60" ) )
table( d_2021$age_cat, useNA = "always" )

# interaction term between age and sex
d_2021$age_sex <- interaction( d_2021$age_cat, d_2021$sex )

# generation
d_2021$birth_year <- 2021 - d_2021$age
d_2021 <- d_2021 %>%
  mutate( generation = case_when(
    birth_year >= 1997 & birth_year <= 2012 ~ "Generation Z (1997–2012)",
    birth_year >= 1981 & birth_year <= 1996 ~ "Millennials (1981–1996)",
    birth_year >= 1965 & birth_year <= 1980 ~ "Generation X (1965–1980)",
    birth_year >= 1946 & birth_year <= 1964 ~ "Baby Boomers (1946–1964)",
    birth_year >= 1928 & birth_year <= 1945 ~ "Silent Generation (1928–1945)",
    birth_year >= 1901 & birth_year <= 1927 ~ "Greatest Generation (1901–1927)"
  ) )

d_2021$generation <- factor( 
  d_2021$generation, 
  levels = c( "Generation Z (1997–2012)", "Millennials (1981–1996)", "Generation X (1965–1980)", "Baby Boomers (1946–1964)", "Silent Generation (1928–1945)", "Greatest Generation (1901–1927)" ) )
summary( d_2021$generation )

# country of birth
table( d_2021$fodelseland, useNA = "always" )
d_2021$country_of_birth <- factor( ifelse( d_2021$fodelseland == "Sverige", "Sweden",
                                           ifelse( d_2021$fodelseland == "Europa", "Europe", "Outside Europe" ) ),
                                   levels = c( "Sweden", "Europe", "Outside Europe" ) )
table( d_2021$country_of_birth, useNA = "always" )

# education
table( d_2021$utbniva2021, useNA = "always" )
d_2021$education <- factor( ifelse( d_2021$utbniva2021 <= 2, "<=9 years",
                                    ifelse( d_2021$utbniva2021 <= 4, "10-12 years", ">=13 years" ) ),
                            levels = c( "<=9 years", "10-12 years", ">=13 years" ) )
table( d_2021$education, useNA = "always" )

# disposable income
summary( d_2021$dispink2021, useNA = "always" )
d_2021$dispink2021[ d_2021$dispink2021 < 0 ] <- NA
d_2021$income <- factor( ifelse( d_2021$dispink2021 <= 2500, "<=2,500",
                                 ifelse( d_2021$dispink2021 > 2500 & d_2021$dispink2021 <= 3500, "(2,500, 3,500]",
                                         ifelse( d_2021$dispink2021 > 3500 & d_2021$dispink2021 <= 4500, "(3,500, 4,500]", ">4,500" ) ) ),
                         levels = c( "<=2,500", "(2,500, 3,500]", "(3,500, 4,500]", ">4,500" ) )
table( d_2021$income, useNA = "always" )

# marital status
table( d_2021$civil2021, useNA = "always" )
d_2021$marital_status <- factor( ifelse( d_2021$civil2021 == "G" | d_2021$civil2021 == "RP", "Currently married",
                                         ifelse( d_2021$civil2021 == "OG", "Never married", "Other" ) ), 
                                 levels = c( "Never married", "Currently married", "Other" ) )
table( d_2021$marital_status, useNA = "always" )

# occupation
table( d_2021$SSYK_kl, useNA = "always" )
d_2021$occupation <- factor(
  ifelse(
    d_2021$SSYK_kl == "Yrken inom byggverksamhet och tillverkning" |
      d_2021$SSYK_kl == "Yrken inom lantbruk, trädgård, skogsbruk och fiske" |
      d_2021$SSYK_kl == "Yrken inom maskinell tillverkning och transport m.m.",
    "Manual and field trades",
    ifelse(
      d_2021$SSYK_kl == "Service-, omsorgs- och försäljningsyrken" |
        d_2021$SSYK_kl == "Yrken inom administration och kundtjänst" |
        d_2021$SSYK_kl == "Yrken med krav på kortare utbildning eller introduktion",
      "Service and support",
      ifelse(
        d_2021$SSYK_kl == "Yrken med krav på fördjupad högskolekompetens" |
          d_2021$SSYK_kl == "Yrken med krav på högskolekompetens eller motsvarande" |
          d_2021$SSYK_kl == "Chefsyrken",
        "Expertise and leadership",
        NA
      )
    )
  ),
  levels = c(
    "Manual and field trades",
    "Service and support",
    "Expertise and leadership"
  )
)
table( d_2021$occupation, useNA = "always" )


##### demographic characteristics #####

# among respondents (n = 23,066)
# make characteristics table by sexual identity
explanatory =  c( "sex", "age_cat", "country_of_birth", "education", "occupation", "income", "marital_status" )
dependent = "sexual_identity_2021"

d_2021_table <- d_2021 %>% 
  summary_factorlist( dependent,
                      explanatory, 
                      na_include = TRUE,
                      na_include_dependent = TRUE, 
                      total_col = TRUE,
                      add_col_totals = TRUE,
                      column = FALSE )

# Fisher's test
x1 <- table( d_2021$sex, d_2021$sexual_identity_2021 )
x1
format( round( fisher.test( x1[, c( 1:2 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x1[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x1[, c( 1, 4 ) ] )$p.value, 3 ), nsmall = 3 )

x2 <- table( d_2021$age_cat, d_2021$sexual_identity_2021 )
x2
format( round( fisher.test( x2[, c( 1:2 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x2[, c( 1, 3 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x2[, c( 1, 4 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

x3 <- table( d_2021$country_of_birth, d_2021$sexual_identity_2021 )
x3
format( round( fisher.test( x3[, c( 1:2 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x3[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x3[, c( 1, 4 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

x4 <- table( d_2021$education, d_2021$sexual_identity_2021 )
x4
format( round( fisher.test( x4[, c( 1:2 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x4[, c( 1, 3 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x4[, c( 1, 4 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

x5 <- table( d_2021$income, d_2021$sexual_identity_2021 )
x5
format( round( fisher.test( x5[, c( 1:2 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x5[, c( 1, 3 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x5[, c( 1, 4 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

x6 <- table( d_2021$marital_status, d_2021$sexual_identity_2021 )
x6
format( round( fisher.test( x6[, c( 1:2 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x6[, c( 1, 3 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x6[, c( 1, 4 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

x7 <- table( d_2021$occupation, d_2021$sexual_identity_2021 )
x7
format( round( fisher.test( x7[, c( 1:2 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x7[, c( 1, 3 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x7[, c( 1, 4 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )


##### design weights #####

summary( d_2021$F21dvikt )
d_2021$design_weight <- d_2021$F21dvikt


##### calibrated weights #####
d_2021$calibrated_weight <- d_2021$F21kalvikt


##### non-response #####

# unit non-response
d_2021$design_weight_unit_nonresponse <- d_2021$F21dbvikt # weights calculated assuming Missing Completely At Random (MCAR) within each stratum
summary( d_2021$design_weight_unit_nonresponse )
sum( d_2021$design_weight_unit_nonresponse ) # No. of source population = 1,827,424

unitresponse_prob <- d_2021 %>% 
  group_by( sampling_strata_region ) %>% 
  summarise( unitresponse_prob = unique( design_weight ) / unique( design_weight_unit_nonresponse ),
             no.of.population = sum( design_weight_unit_nonresponse ),
             sample_size = unique( no.of.population )/unique( design_weight ) ) # calculate overall unit response rate, and no. of population and sample size within each stratum

d_2021 <- d_2021 %>% 
  left_join( unitresponse_prob, by = "sampling_strata_region" )

# item non-response
itemresponse_prob <- d_2021 %>% 
  group_by( sampling_strata_region ) %>% 
  summarise( itemresponse_prob = sum( !is.na( sexual_identity_2021 ) ) / n() ) # calculate item response rate

d_2021 <- d_2021 %>% 
  left_join( itemresponse_prob, by = "sampling_strata_region" ) %>% 
  mutate( itemresponse_prob = ifelse( is.na( sexual_identity_2021 ), 0, itemresponse_prob ) )


##### summary of stratified sampling #####

sampling_frame_2021 <- as.data.frame( d_2021 %>% 
                                   group_by( sampling_strata_region ) %>% 
                                   reframe( no.of.population = unique( no.of.population ), 
                                            sample_size = unique( no.of.population/design_weight ),
                                            unitresponse = n(),
                                            itemresponse = sum( itemresponse_prob != 0 ) ) )

sampling_frame_2021$unitresponse_rate <- sampling_frame_2021$unitresponse/sampling_frame_2021$sample_size
sampling_frame_2021$itemresponse_rate <- sampling_frame_2021$itemresponse/sampling_frame_2021$unitresponse
sampling_frame_2021$overallresponse_rate <- sampling_frame_2021$itemresponse/sampling_frame_2021$sample_size

sampling_frame_2021$unitresponse_label <- paste0( sampling_frame_2021$unitresponse, " (", 
                                             sprintf( "%.1f", sampling_frame_2021$unitresponse_rate*100 ), "%)" )
sampling_frame_2021$overallresponse_label <- paste0( sampling_frame_2021$itemresponse, " (", 
                                                sprintf( "%.1f", sampling_frame_2021$overallresponse_rate*100 ), "%)" )

round( sum( sampling_frame_2021$unitresponse )/( sum( sampling_frame_2021$sample_size ) ), 3 ) # overall unit response rate
round( sum( sampling_frame_2021$itemresponse )/( sum( sampling_frame_2021$unitresponse ) ), 3 ) # overall item response rate
round( sum( sampling_frame_2021$itemresponse )/( sum( sampling_frame_2021$sample_size ) ), 3 ) # overall response rate

writexl::write_xlsx( sampling_frame_2021, "sampling_frame_2021.xlsx" )


##### replicating non-respondent rows for sampling design #####

# because d_2021 includes data only for respondents (unit response), we need to duplicate rows for non-respondents
# so that the final dataset represents the sampling process
rows_to_add <- d_2021 %>%
  group_by( sampling_strata_region ) %>%
  summarise( to_add = unique( sample_size ) - n(),
             no.of.population = unique( no.of.population ),
             sample_size = unique( sample_size ),
             design_weight = unique( design_weight ) )

sum( rows_to_add$to_add ) # 24,819 non-respondents

rows_to_add$to_add <- round( rows_to_add$to_add ) # to resolve floating-point precision issues

replicated_rows <- rows_to_add[ rep( row.names( rows_to_add ), rows_to_add$to_add ), c( 1, 3:5 ) ]

d_2021_complete <- bind_rows( d_2021, replicated_rows ) # 47,885 individuals in the original sample
```

### 3. Self-Reported Health Outcomes
#### 3.1. Complete-case analysis
##### 3.1.1. Prepare dataset
```{r}
##### mental health outcomes #####

# recent psychological distress
summary( d_2021_complete$F21Kessler6 )
d_2021_complete$psychological_distress <- factor( ifelse( d_2021_complete$F21Kessler6 >= 8, "Yes", "No" ),
                                                  levels = c( "Yes", "No" ) ) # psychological distress defined as a score >= 8
table( d_2021_complete$psychological_distress, useNA = "always" )

# suicidal thoughts
table( d_2021_complete$F21F19_Q31, useNA = "always" )
d_2021_complete$suicidal_thoughts <- factor( 
  case_when(
    d_2021_complete$F21F19_Q31 == 1 ~ "No",
    d_2021_complete$F21F19_Q31 %in% c( 2, 3, 4 ) ~ "Yes"
  ),
  levels = c( "Yes", "No" ) )
table( d_2021_complete$suicidal_thoughts, useNA = "always" )

# suicide attempts
table( d_2021_complete$F21F20_Q32, useNA = "always" )
d_2021_complete$suicide_attempts <- factor( 
  case_when(
    d_2021_complete$F21F20_Q32 == 1 ~ "No",
    d_2021_complete$F21F20_Q32 %in% c( 2, 3, 4 ) ~ "Yes"
  ),
  levels = c( "Yes", "No" ) )
table( d_2021_complete$suicide_attempts, useNA = "always" )


##### behavioral health outcomes #####

# ever cannabis use
table( d_2021_complete$F36_Q48, useNA = "always" )
d_2021_complete$cannabis_use <- factor( if_else( d_2021_complete$F36_Q48 == 1, "No", "Yes" ),
                                        levels = c( "Yes", "No" ) )
table( d_2021_complete$cannabis_use, useNA = "always" )
```

##### 3.1.2. Calculate prevalence
```{r}
# create survey design
d_2021_complete_cc <- d_2021_complete

survey_design_cc <- svydesign( ids = ~ 1, 
                               strata = ~ sampling_strata_region,
                               weights = ~ design_weight,
                               fpc = ~ no.of.population,
                               data = d_2021_complete_cc )

# the following analyses assume MCAR

variables_list <- list(
  list( variable = "psychological_distress", condition = "Yes", name = "psychological_distress" ),
  list( variable = "suicidal_thoughts", condition = "Yes", name = "suicidal_thoughts" ),
  list( variable = "suicide_attempts", condition = "Yes", name = "suicide_attempts" ),
  list( variable = "cannabis_use", condition = "Yes", name = "cannabis_use" )
)

# by sexual identity
results_list <- calculate_svyby_proportion( variables_list = variables_list, 
                                            design = survey_design_cc, 
                                            year = 2021, 
                                            group_var = "sexual_identity_2021" )

self_report_health_outcomes_2021 <- Reduce( function( x, y ){
  merge( x, y, by = "sexual_identity_2021" )
}, 
results_list )

# overall sample
results_list_overall <- calculate_svyby_proportion_overall( 
  variables_list = variables_list,
  design = survey_design_cc,
  year = 2021 )

self_report_health_outcomes_2021_overall <- Reduce( function( x, y ){
  cbind( x, y )
}, 
results_list_overall ) %>% 
  as.data.frame() %>%
  rownames_to_column( var = "sexual_identity_2021" )
self_report_health_outcomes_2021_overall[ 1, 1 ] <- "Stockholm County"

writexl::write_xlsx( rbind( self_report_health_outcomes_2021, self_report_health_outcomes_2021_overall ), "prevalence_cc_self_report_health_outcomes_2021.xlsx" )

# by sex
results_list_by_sex <- calculate_svyby_proportion_subgroup( 
  variables_list = variables_list,
  design = survey_design_cc,
  year = 2021,
  group_var = "sexual_identity_2021 + sex" )

self_report_health_outcomes_2021_by_sex <- Reduce( function( x, y ){
  merge( x, y, by = c( "sexual_identity_2021", "sex" ) )
}, 
results_list_by_sex )
writexl::write_xlsx( self_report_health_outcomes_2021_by_sex, "prevalence_cc_self_report_health_outcomes_2021_by_sex.xlsx" )

# by age
results_list_by_age <- calculate_svyby_proportion_subgroup( 
  variables_list = variables_list,
  design = survey_design_cc,
  year = 2021,
  group_var = "sexual_identity_2021 + age_cat" )

self_report_health_outcomes_2021_by_age <- Reduce( function( x, y ){
  merge( x, y, by = c( "sexual_identity_2021", "age_cat" ) )
}, 
results_list_by_age )
writexl::write_xlsx( self_report_health_outcomes_2021_by_age, "prevalence_cc_self_report_health_outcomes_2021_by_age.xlsx" )
```

### 4. Registry-Based Health Outcomes
#### 4.1. Complete-case analysis
##### 4.1.1. Prepare dataset
```{r}
# use of antidepressants and anxiolytics
atc_2021_all <- read_sas('/Volumes/LGBT Project data/Swedish Registers/atc_2021.sas7bdat') %>%
  filter( !grepl( "^N05CD", ATC ) ) # include participants who had at least one dispensed prescription of N05B or N06A from 2005-06-30 to 2021-12-31

# check variables
summary( atc_2021_all )
length( unique( atc_2021_all$lopnr2 ) ) # 7,505 individuals had any dispensed prescription
unique( atc_2021_all$ATC )
length( intersect( atc_2021_all$lopnr2, d_2021_complete$lopnr2 ) )

atc_2021 <- atc_2021_all %>%
  select( "lopnr2", "ATC", "EDATUM" ) %>%
  mutate( 
    drug_class = as.factor( 
      case_when(
        grepl( "^N06A", ATC ) ~ "N06A",
        grepl( "^N05B", ATC ) ~ "N05B" ) ),
    year = year( EDATUM ) ) %>%
  filter( year == 2021 ) # select prescription data only in the year 2021

summary( atc_2021 )
length( unique( atc_2021$lopnr2 ) ) # 3,079

atc_2021_summary <- atc_2021 %>%
  group_by( lopnr2, drug_class ) %>%
  summarise( prescription_count_2021 = n(), .groups = "drop" )

atc_2021_summary_wide <- atc_2021_summary %>%
  pivot_wider(
    names_from = drug_class,
    values_from = prescription_count_2021,
    names_prefix = "prescription_count_2021_",
    values_fill = 0
  ) %>%
  mutate(
    prescribed_2021_N06A = factor( if_else( prescription_count_2021_N06A > 0, "Yes", "No" ) ),
    prescribed_2021_N05B = factor( if_else( prescription_count_2021_N05B > 0, "Yes", "No" ) ) )
summary( atc_2021_summary_wide )

d_2021_complete_cc_linked <- d_2021_complete %>%
  left_join( atc_2021_summary_wide, by = "lopnr2" ) %>%
  mutate(
    prescription_count_2021_N06A = if_else( !is.na( lopnr2 ) & is.na( prescription_count_2021_N06A ), 0, prescription_count_2021_N06A ),
    prescription_count_2021_N05B = if_else( !is.na( lopnr2 ) & is.na( prescription_count_2021_N05B ), 0, prescription_count_2021_N05B ),
    prescribed_2021_N06A = factor( if_else( !is.na( lopnr2 ) & is.na( prescribed_2021_N06A ), "No", prescribed_2021_N06A ) ),
    prescribed_2021_N05B = factor( if_else( !is.na( lopnr2 ) & is.na( prescribed_2021_N05B ), "No", prescribed_2021_N05B ) )
  )

# cross check data
summary( d_2021_complete_cc_linked$prescription_count_2021_N06A )
sum( d_2021_complete_cc_linked$prescription_count_2021_N06A, na.rm = TRUE )
sum( atc_2021_summary_wide$prescription_count_2021_N06A )
summary( d_2021_complete_cc_linked$prescription_count_2021_N05B )
sum( d_2021_complete_cc_linked$prescription_count_2021_N05B, na.rm = TRUE )
sum( atc_2021_summary_wide$prescription_count_2021_N05B )
table( d_2021_complete_cc_linked$prescribed_2021_N06A, useNA = "always" )
table( atc_2021_summary_wide$prescribed_2021_N06A, useNA = "always" )
table( d_2021_complete_cc_linked$prescribed_2021_N05B, useNA = "always" )
table( atc_2021_summary_wide$prescribed_2021_N05B, useNA = "always" )

# assume complete follow-up through registry during 2021 among SPHC-B 2021 participants

# create survey design
# use calibrated weights to account for unit non-response
survey_design_cc <- svydesign( ids = ~ 1, 
                               strata = ~ sampling_strata_region,
                               weights = ~ calibrated_weight,
                               fpc = ~ no.of.population,
                               data = d_2021_complete_cc_linked[ !is.na( d_2021_complete_cc_linked$lopnr2 ), ] )
```

##### 4.1.2. Calculate prevalence
```{r}
variables_list <- list(
  list( variable = "prescribed_2021_N06A", condition = "Yes", name = "prescribed_2021_N06A" ),
  list( variable = "prescribed_2021_N05B", condition = "Yes", name = "prescribed_2021_N05B" )
)

# by sexual identity
results_list <- calculate_svyby_proportion( variables_list = variables_list, 
                                            design = survey_design_cc, 
                                            year = 2021, 
                                            group_var = "sexual_identity_2021" )

pdr_2021 <- Reduce( function( x, y ){
  merge( x, y, by = "sexual_identity_2021" )
}, 
results_list )

# overall sample
results_list_overall <- calculate_svyby_proportion_overall( 
  variables_list = variables_list,
  design = survey_design_cc,
  year = 2021 )

pdr_2021_overall <- Reduce( function( x, y ){
  cbind( x, y )
}, 
results_list_overall ) %>% 
  as.data.frame() %>%
  rownames_to_column( var = "sexual_identity_2021" )
pdr_2021_overall[ 1, 1 ] <- "Stockholm County"

writexl::write_xlsx( rbind( pdr_2021, pdr_2021_overall ), "prevalence_pdr_2021.xlsx" )

# by sex
results_list_by_sex <- calculate_svyby_proportion_subgroup( 
  variables_list = variables_list,
  design = survey_design_cc,
  year = 2021,
  group_var = "sexual_identity_2021 + sex" )

pdr_2021_by_sex <- Reduce( function( x, y ){
  merge( x, y, by = c( "sexual_identity_2021", "sex" ) )
}, 
results_list_by_sex )
writexl::write_xlsx( pdr_2021_by_sex, "prevalence_pdr_2021_by_sex.xlsx" )

# by age
results_list_by_age <- calculate_svyby_proportion_subgroup( 
  variables_list = variables_list,
  design = survey_design_cc,
  year = 2021,
  group_var = "sexual_identity_2021 + age_cat" )

pdr_2021_by_age <- Reduce( function( x, y ){
  merge( x, y, by = c( "sexual_identity_2021", "age_cat" ) )
}, 
results_list_by_age )
writexl::write_xlsx( pdr_2021_by_age, "prevalence_pdr_2021_by_age.xlsx" )
```

##### 4.1.3. Calculate number of dispensed prescriptions
```{r}
variables_list <- c( "prescription_count_2021_N06A", "prescription_count_2021_N05B" )

# by sexual identity
results_list <- calculate_svyby_count( variables_list = variables_list, 
                                       design = survey_design_cc, 
                                       group_var = "sexual_identity_2021" )

pdr_2021 <- Reduce( function( x, y ){
  merge( x, y, by = "sexual_identity_2021" )
}, 
results_list )

# overall sample
results_list_overall <- calculate_svyby_count_overall( 
  variables_list = variables_list,
  design = survey_design_cc )

pdr_2021_overall <- Reduce( function( x, y ){
  cbind( x, y )
}, 
results_list_overall ) %>% 
  as.data.frame() %>%
  rownames_to_column( var = "sexual_identity_2021" )
pdr_2021_overall[ 1, 1 ] <- "Stockholm County"

writexl::write_xlsx( rbind( pdr_2021, pdr_2021_overall ), "count_pdr_2021.xlsx" )

# by sex
results_list_by_sex <- calculate_svyby_count_subgroup( 
  variables_list = variables_list,
  design = survey_design_cc,
  group_var = "sexual_identity_2021 + sex" )

pdr_2021_by_sex <- Reduce( function( x, y ){
  merge( x, y, by = c( "sexual_identity_2021", "sex" ) )
}, 
results_list_by_sex )
writexl::write_xlsx( pdr_2021_by_sex, "count_pdr_2021_by_sex.xlsx" )

# by age
results_list_by_age <- calculate_svyby_count_subgroup( 
  variables_list = variables_list,
  design = survey_design_cc,
  group_var = "sexual_identity_2021 + age_cat" )

pdr_2021_by_age <- Reduce( function( x, y ){
  merge( x, y, by = c( "sexual_identity_2021", "age_cat" ) )
}, 
results_list_by_age )
writexl::write_xlsx( pdr_2021_by_age, "count_pdr_2021_by_age.xlsx" )
```
